<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link, useForm } from '@inertiajs/vue3';
const props = defineProps({ user: Object, roles: Array });
const form = useForm({ name: props.user?.name || '', email: props.user?.email || '', password: '', password_confirmation: '', role_id: props.user?.role_id || props.roles?.[0]?.id || '' });
const submit = () => props.user ? form.put(route('admin.users.update', props.user.id)) : form.post(route('admin.users.store'));
</script>
<template><Head :title="user ? 'Sửa nhân viên' : 'Thêm nhân viên'"/><AuthenticatedLayout><template #header><h2 class="text-lg font-bold uppercase text-emerald-950">{{ user ? 'Sửa tài khoản nhân viên' : 'Tạo tài khoản nhân viên' }}</h2></template>
<form class="mx-auto max-w-2xl space-y-6 rounded-lg border border-zinc-200 bg-white p-7" @submit.prevent="submit"><div v-if="Object.keys(form.errors).length" class="rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><p v-for="error in form.errors" :key="error">{{ error }}</p></div>
<div class="grid gap-5 md:grid-cols-2"><div><label class="text-sm font-bold">Họ và tên *</label><input v-model="form.name" required class="mt-2 w-full rounded-lg border-zinc-200"/></div><div><label class="text-sm font-bold">Email *</label><input v-model="form.email" type="email" required class="mt-2 w-full rounded-lg border-zinc-200"/></div><div><label class="text-sm font-bold">Mật khẩu {{ user ? '(để trống nếu không đổi)' : '*' }}</label><input v-model="form.password" type="password" :required="!user" class="mt-2 w-full rounded-lg border-zinc-200"/></div><div><label class="text-sm font-bold">Xác nhận mật khẩu</label><input v-model="form.password_confirmation" type="password" :required="!!form.password" class="mt-2 w-full rounded-lg border-zinc-200"/></div></div>
<div><label class="text-sm font-bold">Vai trò *</label><select v-model="form.role_id" required class="mt-2 w-full rounded-lg border-zinc-200"><option v-for="role in roles" :key="role.id" :value="role.id">{{ role.name }} ({{ role.permissions.length }} quyền)</option></select><p class="mt-2 text-xs text-zinc-500">Quyền của tài khoản được quản lý tập trung trong module Vai trò & Phân quyền.</p></div>
<div class="flex justify-end gap-3"><Link :href="route('admin.users.index')" class="rounded-lg border px-5 py-2.5">Hủy</Link><button class="rounded-lg bg-[#043616] px-6 py-2.5 font-semibold text-white">Lưu nhân viên</button></div></form></AuthenticatedLayout></template>
